[package]
name = "afk"
version = "0.1.0"
authors = ["Togglebit <me@togglebit.io>"]
edition = "2021"

[dependencies]
figglebit = { git = "https://github.com/togglebyte/figglebit" }
crossterm = "0.18.1"
ansi_term = "0.12.1"
